from __future__ import annotations

SOURCE_FIELDS = [
    "retrieved_at",
    "source_batch",
    "source_name",
    "source_url",
    "source_type",
    "record_type",
    "name",
    "role_title",
    "institution",
    "department_or_group",
    "country",
    "summary_text",
    "keyword_hits",
    "homepage_url",
    "orcid_url",
    "scholar_url",
    "metric_h_index",
    "metric_source",
    "citation_count",
    "honors",
    "raw_text",
    "extraction_method",
    "notes",
]

ENTITY_FIELDS = [
    "retrieved_at",
    "source_batch",
    "source_name",
    "source_url",
    "all_source_urls",
    "all_source_names",
    "name",
    "role_title",
    "institution",
    "department_or_group",
    "country",
    "summary_text",
    "domain_tags",
    "homepage_url",
    "orcid_url",
    "scholar_url",
    "openalex_url",
    "semantic_scholar_url",
    "h_index",
    "citation_count",
    "metric_source",
    "honors",
    "target_venue_exact",
    "target_venue_family",
    "target_publication_evidence",
    "relevance_status",
    "relevance_reason",
    "relevance_evidence",
    "notes",
]

POSITION_FIELDS = [
    "retrieved_at",
    "source_name",
    "source_query",
    "title",
    "url",
    "institution",
    "location",
    "deadline",
    "open_status",
    "host_or_group",
    "role_type",
    "domain_tags",
    "relevance_status",
    "relevance_reason",
    "description_snippet",
    "constraints",
    "notes",
]

STATUS_FIELDS = [
    "person_key",
    "name",
    "institution",
    "status",
    "priority",
    "last_contacted",
    "next_action_date",
    "private_note",
    "updated_at",
]

REQUIRED_ENTITY_FIELDS = [
    "name",
    "institution",
    "country",
    "summary_text",
    "relevance_status",
    "relevance_evidence",
]

FIELD_DESCRIPTIONS = {
    "retrieved_at": "UTC timestamp for when this source or fact snapshot was collected.",
    "source_batch": "Stable name for the source pass that produced the row.",
    "source_name": "Human-readable source name, such as a lab page, directory, journal/conference list, or job board.",
    "source_url": "Primary URL used for this row.",
    "source_type": "Category of source, such as profile_source, reverse_discovery, publication_source, or position_source.",
    "record_type": "Kind of raw record extracted from a source, such as person, group, role, or publication.",
    "name": "Person or group lead name as presented by the verified source.",
    "role_title": "Role title from the source, without using it as proof of current status unless retrieved recently.",
    "institution": "Current or source-stated institution for the person or group.",
    "department_or_group": "Department, lab, group, center, or program name.",
    "country": "Country or main location for the person, group, or role.",
    "summary_text": "Short factual summary of research area, group focus, or role fit.",
    "keyword_hits": "Raw keywords matched during extraction; useful for audits, not final classification by itself.",
    "raw_text": "Relevant source text snippet preserved for auditability.",
    "extraction_method": "How the row was produced, such as manual extraction, official page crawl, API lookup, or synthetic seed.",
    "all_source_urls": "Merged provenance URLs for a final entity row, separated by semicolons.",
    "all_source_names": "Merged provenance source names for a final entity row, separated by semicolons.",
    "domain_tags": "Project-defined tags used for filtering and grouping; separate multiple tags with semicolons.",
    "homepage_url": "Official homepage, lab page, or institutional profile URL.",
    "orcid_url": "ORCID URL when verified.",
    "scholar_url": "Google Scholar or equivalent profile URL when verified.",
    "openalex_url": "OpenAlex author or institution URL when verified.",
    "semantic_scholar_url": "Semantic Scholar author URL when verified.",
    "h_index": "Bibliometric h-index snapshot from the stated metric source.",
    "citation_count": "Bibliometric citation-count snapshot from the stated metric source.",
    "metric_h_index": "Raw-source h-index value before final entity normalization.",
    "metric_source": "Source and retrieval context for metrics; leave values blank rather than guessing.",
    "honors": "Awards, fellowships, invited distinctions, or comparable recognition relevant to prioritization.",
    "target_venue_exact": "yes/no flag for verified evidence in the project-configured target journal/conference list.",
    "target_venue_family": "yes/no flag for verified evidence in the related journal/conference family list configured by the project.",
    "target_publication_evidence": "Concise evidence for target journal/conference or related journal/conference publications.",
    "relevance_status": "Classification such as include, review, adjacent, excluded, or stale.",
    "relevance_reason": "Short machine-readable reason for the classification.",
    "relevance_evidence": "Human-readable evidence explaining why the row is included or held for review.",
    "notes": "Caveats, unresolved issues, manual decisions, or source limitations.",
    "source_query": "Query or source-pass label used to discover a role.",
    "title": "Position or opportunity title.",
    "url": "Opportunity URL.",
    "location": "Position location, remote policy, or host location.",
    "deadline": "Application deadline as stated by the source.",
    "open_status": "Current visibility or status of a role, such as open, closed, unknown, or archived.",
    "host_or_group": "Host person, lab, group, center, or team for a role.",
    "role_type": "Opportunity type, such as postdoc, fellowship, staff scientist, visiting role, or internship.",
    "description_snippet": "Short sourced snippet describing the role.",
    "constraints": "Eligibility, citizenship, location, visa, duration, or funding constraints.",
    "person_key": "Normalized key derived from name and institution for joining private status to public facts.",
    "status": "Private workflow state, such as none, to_apply, shortlist, contacted, waiting_reply, follow-up, applied, or rejected.",
    "priority": "Private user priority, typically high, medium, low, or blank.",
    "last_contacted": "Private date for the most recent outreach action.",
    "next_action_date": "Private date for the next planned action.",
    "private_note": "Private note that must remain in the status sidecar, not in public fact tables.",
    "updated_at": "UTC timestamp for the latest private status update.",
}


def all_schema_fields() -> set[str]:
    return set(SOURCE_FIELDS) | set(ENTITY_FIELDS) | set(POSITION_FIELDS) | set(STATUS_FIELDS)
